#!/bin/bash

sm="../sm"

path="$1"
base=$(dirname $path)
file=$(basename $path)

if [ "$file" = "" ]; then
    echo "Usage: $0 path/to/file.test" >&2
    exit 1
fi

id=$(echo $file | sed -r 's/(-[^-]+){1}.test//g')
prev=$(echo $path | sed -r 's/.test/.prev/g')
parse=$base/parse
conf=$base/$id.conf
args=$id
options=$(grep $file $base/*.args | head -n 1 | cut -d" " -f 3-)
tmp=$(mktemp -d)

# Prepare environment with previous executions
if [ -f "$prev" ]; then
    while read line; do
        $sm -c $conf -o $tmp ${line[0]} >> $tmp/prev
    done < "$prev"
fi

$sm -c $conf -o $tmp $options > $tmp/stdout

diff=$(./$parse < $tmp/stdout | diff -u $path -)
status=$?

rm -rf $tmp

if [ $status -eq 0 ]; then
    echo "$file: OK"
    exit 0
fi

echo "$file: FAILED"
echo "$diff"
exit 1
