#!/bin/bash

sm="../sm"
data="../data"

file="$1"

if [ "$file" = "" ]; then
    echo "Usage: $0 file.test" >&2
    exit 1
fi

id=$(echo $file | cut -d"-" -f 1)
bin=$(echo $file | sed -r 's/(-[^-]+){1}.test//g')
conf=$bin.conf
args=$bin.args
options=$(grep $file *.args | head -n 1 | cut -d" " -f 3-)
tmp=$(mktemp -d)

find $PWD/$id*.fq.gz > $tmp/input-file

$sm -c $conf -i $tmp/input-file -o $tmp $options > $tmp/stdout

diff=$(./$bin < $tmp/stdout | diff -u $file -)
status=$?

rm -rf $tmp

if [ $status -eq 0 ]; then
    echo "$file: OK"
    exit 0
fi

echo "$file: FAILED"
echo "$diff"
exit 1
